# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 SuperNovae Studio <contact@supernovae.studio>
#
# Per-repo estate rules. The tool is shared and lives in nika-estate; these
# declarations are ours. FILES carries the per-file exceptions, PATTERNS the
# ordered globs that cover everything else (first match wins).
#
# This module is CODE, not data: the rows below that depend on what is
# actually in the tree (the generated snippets fire only when their in-file
# marker is present; a poster frame is only a poster if its video twin
# exists) are computed at import, exactly as the schema-1 classify() did.
# Nothing is asserted that the bytes do not show.
#
# The tool hands down ROOT, SELF, RULES and CLASSES before executing this.

import pathlib
import subprocess

GATE_YML = ".github/workflows/gate.yml"
HEAL_YML = ".github/workflows/release-heal.yml"


def _tracked() -> list:
    out = subprocess.run(["git", "-C", str(ROOT), "ls-files", "-z"],  # noqa: F821
                         capture_output=True, check=True)
    return sorted(f for f in out.stdout.decode().split("\0") if f)


def _head(rel: str, n: int = 4) -> str:
    """The first n lines, or "" for anything unreadable as text."""
    try:
        return "\n".join((ROOT / rel).read_text().splitlines()[:n])  # noqa: F821
    except (UnicodeDecodeError, OSError):
        return ""


# The generated snippets. Classification fires ONLY when the in-file
# AUTO-GENERATED marker is actually present: evidence-driven, never assumed.
# _status-snapshot.mdx used to sit here with a note saying its header
# over-claimed; 2026-07-27 the header was rewritten to stop over-claiming, so
# it classifies as authored below, where a mostly-hand-typed file belonged.
_GENERATED = {
    "snippets/_canon.mdx": {
        "evidence": "in-file marker: '{/* _canon.mdx — AUTO-GENERATED by scripts/canon-projectors.py (nika-spec repo) from canon.yaml'",
        "derivation": {
            "tool": "python3 scripts/canon-projectors.py --write (runs in the supernovae-st/nika-spec checkout — the tool does NOT live in this repo)",
            "gate": "EXTERNAL — canon-projectors.py --check is wired into the SuperNovae run-all audit (its own marker's claim); no step in .github/workflows/gate.yml re-proves this file",
            "inputs": ["supernovae-st/nika-spec canon.yaml (the Nika language single source of truth)"],
        },
    },
    "snippets/_showcase.mdx": {
        "evidence": "in-file marker: '{/* _showcase.mdx — AUTO-GENERATED by scripts/showcase-projector.py (nika-spec repo) from examples/showcase/'",
        "derivation": {
            "tool": "python3 scripts/showcase-projector.py --write (runs in the supernovae-st/nika-spec checkout — the tool does NOT live in this repo)",
            "gate": "NONE in this repo — no gate.yml step re-derives the showcase counts; sync rides the spec-side projector runs",
            "inputs": ["supernovae-st/nika-spec examples/showcase/ (tier counts derive · never hand-typed)"],
        },
    },
}

# The named roles. Schema 2 gained two words schema 1 did not have, and one
# of these rows finally gets the right one: LICENSE is a verbatim upstream
# text placed here byte for byte, which is what `pinned-copy` means. Calling
# it `authored` claimed a human wrote the AGPL, which no human here did.
_AUTHORED = {
    "README.md": "prose entry surface · no generation marker",
    "AGENTS.md": "hand-written agent entry per the AGENTS.md convention · it STATES the projection rules the snippets follow",
    "DEPLOY.md": "hand-written deploy runbook (Mintlify dashboard + DNS steps · two owners)",
    "SECURITY.md": "hand-written security policy (copy-paste surface + llms.txt threat model)",
    ".nvmrc": "hand-pinned Node major for the local mint preview",
    "docs.json": "hand-written Mintlify config (nav + theme + metadata) · no generation marker",
    "global.css": "hand-written polish layer · its own header: 'colors + fonts live in docs.json · pinned to … nika-spec design/tokens.yaml … this file = the polish layer'",
    "lefthook.yml": "hand-written pre-push gate config (mint broken-links · link-audit · teach-parity · oracle-sweep)",
    ".github/dependabot.yml": "hand-written grouped-bumps policy (comments narrate the nika-spec PR #135 desync lesson)",
    GATE_YML: "hand-written CI trust model (comments narrate the judge choices — released-binary oracle · wire-asserted counts)",
    HEAL_YML: "hand-written bot workflow (it edits snippets/_status-snapshot.mdx — nothing writes it)",
    "scripts/count-drift-gate.py": "hand-written gate · 'the count-rot ratchet' design prose header",
    "scripts/link-audit.py": "hand-written gate · docstring lists its four checks (links · nav · dead branches · legacy bindings)",
    "scripts/oracle-sweep.py": "hand-written gate · SPDX header + the copy-paste-invariant design prose",
    "scripts/teach-parity.py": "hand-written gate · docstring states its law (both directions read the binary's own --help)",
    "scripts/mintlify-snapshot.sh": "hand-written healer script (the tool that derives _status-snapshot.mdx's two release fields)",
    RULES: "hand-written per-repo estate rules (this file) · the tool is shared, these declarations are ours",  # noqa: F821
    "snippets/_ecosystem.mdx": "its own header: 'Edit HERE, never per-page' — the one hand-edited snippet (a single-source link mesh, not a projection)",
    "snippets/_status-snapshot.mdx": "its own header: 'MIXED PROVENANCE' — scripts/mintlify-snapshot.sh derives version + lastUpdated ONLY; every count field is hand-typed, so the file is authored with two bot-maintained fields",
    "reference/error-codes.mdx": "hand-written MDX page (frontmatter + prose · no generation marker · volatile counts import the generated snippets per AGENTS.md rule 1)",
    "reference/mcp-catalog.mdx": "hand-written MDX page (frontmatter + prose · no generation marker · volatile counts import the generated snippets per AGENTS.md rule 1)",
}

_NOTES = {
    "docs.json": "theme colors follow the nika-spec design-tokens SSOT — advisory parity gate: gate.yml step 'docs.json theme parity vs the design-tokens SSOT (advisory)' (continue-on-error)",
    HEAL_YML: "release-heal rewrites the version + lastUpdated fields of snippets/_status-snapshot.mdx on a daily cron — bot-maintained fields in ANOTHER file, this one stays hand-written",
    "snippets/_status-snapshot.mdx": "the daily release-heal cron rewrites version + lastUpdated here, which advances lastUpdated while the hand-typed counts stay frozen — a fresh date is NOT evidence of fresh counts. No gate watches the counts: engine hygiene vector 23's whitelist (ROADMAP.md · .claude/CLAUDE.md) resolves against the ENGINE repo root and cannot see this one. The file header carries the per-field derivation commands.",
    "reference/error-codes.mdx": "its own prose claims 'The tables below are generated from that registry' (the spec's canon.yaml) — but no projector writes this file and no gate re-proves the tables: a hand-baked derivation snapshot, not a projection",
    "reference/mcp-catalog.mdx": "frontmatter description hand-types '105 MCP server entries … snapshot 2026-04-17' — outside count-drift-gate's checked classes (providers · builtins · extract modes), so it can rot silently",
}

_LICENSE_EVIDENCE = ("verbatim GNU AGPL-3.0 text from the FSF, placed here byte for byte "
                     "· no human in this repo wrote it, which is why it is not authored")


# ── FILES · the per-file exceptions, computed from what the tree shows ──────

_MIRROR_ROWS = [
    {"path": SELF, "class": "pinned-copy", "evidence": "the shared estate tool, mirrored byte-for-byte from supernovae-st/nika-estate · editing it here is a lost gesture: change it upstream, bump ESTATE_PIN, re-mirror",  # noqa: F821
      "derivation": {
            "tool": "curl the tool from nika-estate at the rev named in ESTATE_PIN",
            "gate": "the `mirror` job byte-compares scripts/estate.py against nika-estate@ESTATE_PIN and fails the run on any difference",
            "inputs": ["ESTATE_PIN", "supernovae-st/nika-estate@<ESTATE_PIN>:scripts/estate.py"],
        }},
    {"path": "ESTATE_PIN", "class": "authored-pin",
      "evidence": "its own header: 'Bump deliberately: edit this' \u00b7 the rev the shared estate tool is mirrored from, and the INPUT the mirror gate compares against"},
]

FILES = []

for _rel, _spec in _GENERATED.items():
    if "AUTO-GENERATED by" in _head(_rel):
        FILES.append({"path": _rel, "class": "generated",
                      "evidence": _spec["evidence"], "derivation": _spec["derivation"]})
    else:
        # The marker went away: say so rather than keep claiming a projection.
        FILES.append({"path": _rel, "class": "authored",
                      "evidence": "expected an AUTO-GENERATED marker in the first lines and found none",
                      "note": "unverified-default"})

for _rel, _ev in _AUTHORED.items():
    _row = {"path": _rel, "class": "authored", "evidence": _ev}
    if _rel in _NOTES:
        _row["note"] = _NOTES[_rel]
    FILES.append(_row)

FILES.append({
    "path": "LICENSE", "class": "pinned-copy", "evidence": _LICENSE_EVIDENCE,
    "derivation": {
        "tool": "hand-placed from the FSF canonical text",
        "gate": "NONE — no step re-fetches the upstream text; the SPDX identifier in every source header is the only cross-check",
        "inputs": ["https://www.gnu.org/licenses/agpl-3.0.txt (GNU AGPL-3.0, verbatim)"],
    },
})

# Poster frames: a bitmap under images/ is a poster only if its video twin is
# tracked. Computed, because the pairing lives in the tree, not in a glob.
_VIDEO_STEMS = {pathlib.Path(f).stem for f in _tracked()
                if f.startswith("videos/") and f.endswith((".mp4", ".webm"))}
for _f in _tracked():
    _stem = pathlib.Path(_f).stem
    if _f.startswith("images/") and _f.endswith(".png") and _stem in _VIDEO_STEMS:
        FILES.append({
            "path": _f, "class": "authored",
            "evidence": f"poster frame paired with videos/{_stem}.mp4/.webm (wired as the <video poster=…>) · extraction pipeline is not in this repo",
            "note": "unverified-default",
        })


# ── PATTERNS · ordered, first match wins, over everything FILES did not take ─

PATTERNS = [
    {"glob": "**.mdx", "class": "authored",
     "evidence": "hand-written MDX page (frontmatter + prose · no generation marker · volatile counts import the generated snippets per AGENTS.md rule 1)"},

    {"glob": "videos/**", "class": "authored",
     "evidence": "screen-capture demo video (poster twin under images/) · recording pipeline is not in this repo",
     "note": "unverified-default"},

    {"glob": "images/og-*.png", "class": "authored",
     "evidence": "Open Graph card bitmap wired in docs.json metadata · production pipeline is not in this repo",
     "note": "unverified-default"},

    {"glob": "images/**.svg", "class": "authored",
     "evidence": "brand vector asset (logo/favicon family) · the brand pipeline lives outside this repo",
     "note": "unverified-default"},

    {"glob": "images/**", "class": "authored",
     "evidence": "bitmap asset · no in-repo derivation evidence",
     "note": "unverified-default"},

    # Totality. Anything reaching here has no evidence at all, and the schema-2
    # coverage check would otherwise exit 3 on it: honesty over completeness.
    {"glob": "**", "class": "authored",
     "evidence": "no generation marker or known role found",
     "note": "unverified-default"},
]

FILES.extend(_MIRROR_ROWS)
