#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 SuperNovae Studio <contact@supernovae.studio>
#
# estate.py — the provenance manifest: every tracked file declares what it IS.
#
# OBSERVATION MODE (E0): estate.yaml declares provenance — authored ·
# generated · pinned-copy · foreign — it enforces nothing. The point is to
# make the repo's derivation topology explicit: which files a human writes,
# which files a tool re-derives (and from what, gated by which CI check),
# so drift between "what we believe" and "what is" becomes observable.
#
# Classification is EVIDENCE-driven, never assumed: the script reads the
# generation markers inside the files themselves (the three AUTO-GENERATED
# snippet headers · the _ecosystem.mdx "Edit HERE" header) and knows the
# named roles of the root/gate files. A docs page is authored by
# construction here (AGENTS.md rule 1: pages import the generated snippets
# rather than being generated). A file with no such evidence lands in
# `authored` with `note: unverified-default` — honesty over completeness.
#
# Derived, never authored (the house projection pattern): --write
# regenerates estate.yaml from the tracked tree; --check re-emits and
# byte-compares. On divergence --check exits 5 (the ssot-compiler
# convention — deliberately distinct from the sibling gates' exit 1, so an
# estate divergence is distinguishable in CI logs).
#
# Usage:
#   python3 scripts/estate.py --write   # regenerate estate.yaml
#   python3 scripts/estate.py --check   # drift gate (exit 5 on divergence)

import hashlib
import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ESTATE = ROOT / "estate.yaml"
ESTATE_SCHEMA = 1
SELF = "scripts/estate.py"

CLASSES = {
    "authored": "a human writes here",
    "generated": "derived by a tool from declared inputs — regenerate, never hand-edit",
    "pinned-copy": "byte-copy pinned to an upstream rev",
    "foreign": "pointer to a third-party sovereign source",
}

GATE_YML = ".github/workflows/gate.yml"
HEAL_YML = ".github/workflows/release-heal.yml"


def tracked_files() -> list:
    out = subprocess.run(["git", "-C", str(ROOT), "ls-files", "-z"],
                         capture_output=True, check=True)
    files = {f for f in out.stdout.decode().split("\0") if f}
    # The generator always classifies itself; the manifest never lists
    # itself (its sha256 cannot contain its own hash).
    files.add(SELF)
    files.discard("estate.yaml")
    return sorted(files)


# The generated snippets — classification fires ONLY when the in-file
# AUTO-GENERATED marker is actually present (evidence-driven, never assumed).
# _status-snapshot.mdx used to sit here and carried a `note` saying its header
# over-claimed. 2026-07-27 the header was rewritten to stop over-claiming, so
# the file now classifies as `authored` (below) — where a mostly-hand-typed
# file always belonged.
GENERATED_SNIPPETS = {
    "snippets/_canon.mdx": {
        "evidence": "in-file marker: '{/* _canon.mdx — AUTO-GENERATED by scripts/canon-projectors.py (nika-spec repo) from canon.yaml'",
        "derivation": {
            "tool": "python3 scripts/canon-projectors.py --write (runs in the supernovae-st/nika-spec checkout — the tool does NOT live in this repo)",
            "gate": "EXTERNAL — canon-projectors.py --check is wired into the SuperNovae run-all audit (its own marker's claim); no step in .github/workflows/gate.yml re-proves this file",
            "inputs": ["supernovae-st/nika-spec canon.yaml (the Nika language single source of truth)"],
        },
    },
    "snippets/_showcase.mdx": {
        "evidence": "in-file marker: '{/* _showcase.mdx — AUTO-GENERATED by scripts/showcase-projector.py (nika-spec repo) from examples/showcase/'",
        "derivation": {
            "tool": "python3 scripts/showcase-projector.py --write (runs in the supernovae-st/nika-spec checkout — the tool does NOT live in this repo)",
            "gate": "NONE in this repo — no gate.yml step re-derives the showcase counts; sync rides the spec-side projector runs",
            "inputs": ["supernovae-st/nika-spec examples/showcase/ (tier counts derive · never hand-typed)"],
        },
    },
}

AUTHORED_EVIDENCE = {
    "README.md": "prose entry surface · no generation marker",
    "AGENTS.md": "hand-written agent entry per the AGENTS.md convention · it STATES the projection rules the snippets follow",
    "DEPLOY.md": "hand-written deploy runbook (Mintlify dashboard + DNS steps · two owners)",
    "SECURITY.md": "hand-written security policy (copy-paste surface + llms.txt threat model)",
    "LICENSE": "verbatim GNU AGPL-3.0 license text (FSF canonical text · hand-placed · matches the engine's license)",
    ".nvmrc": "hand-pinned Node major for the local mint preview",
    "docs.json": "hand-written Mintlify config (nav + theme + metadata) · no generation marker",
    "global.css": "hand-written polish layer · its own header: 'colors + fonts live in docs.json · pinned to … nika-spec design/tokens.yaml … this file = the polish layer'",
    "lefthook.yml": "hand-written pre-push gate config (mint broken-links · link-audit · teach-parity · oracle-sweep)",
    ".github/dependabot.yml": "hand-written grouped-bumps policy (comments narrate the nika-spec PR #135 desync lesson)",
    GATE_YML: "hand-written CI trust model (comments narrate the judge choices — released-binary oracle · wire-asserted counts)",
    HEAL_YML: "hand-written bot workflow (it edits snippets/_status-snapshot.mdx — nothing writes it)",
    "scripts/count-drift-gate.py": "hand-written gate · 'the count-rot ratchet' design prose header",
    "scripts/link-audit.py": "hand-written gate · docstring lists its four checks (links · nav · dead branches · legacy bindings)",
    "scripts/oracle-sweep.py": "hand-written gate · SPDX header + the copy-paste-invariant design prose",
    "scripts/teach-parity.py": "hand-written gate · docstring narrates its birth (the untaught `nika context` catch)",
    "scripts/mintlify-snapshot.sh": "hand-written healer script (the tool that derives _status-snapshot.mdx's two release fields)",
    SELF: "hand-written estate projector (this manifest's generator)",
    "snippets/_ecosystem.mdx": "its own header: 'Edit HERE, never per-page' — the one hand-edited snippet (a single-source link mesh, not a projection)",
    "snippets/_status-snapshot.mdx": "its own header: 'MIXED PROVENANCE' — scripts/mintlify-snapshot.sh derives version + lastUpdated ONLY; every count field is hand-typed, so the file is authored with two bot-maintained fields",
}

AUTHORED_NOTES = {
    "docs.json": "theme colors follow the nika-spec design-tokens SSOT — advisory parity gate: gate.yml step 'docs.json theme parity vs the design-tokens SSOT (advisory)' (continue-on-error)",
    HEAL_YML: "release-heal rewrites the version + lastUpdated fields of snippets/_status-snapshot.mdx on a daily cron — bot-maintained fields in ANOTHER file, this one stays hand-written",
    "snippets/_status-snapshot.mdx": "the daily release-heal cron rewrites version + lastUpdated here, which advances lastUpdated while the hand-typed counts stay frozen — a fresh date is NOT evidence of fresh counts. No gate watches the counts: engine hygiene vector 23's whitelist (ROADMAP.md · .claude/CLAUDE.md) resolves against the ENGINE repo root and cannot see this one. The file header carries the per-field derivation commands.",
}

MDX_NOTES = {
    "reference/error-codes.mdx": "its own prose claims 'The tables below are generated from that registry' (the spec's canon.yaml) — but no projector writes this file and no gate re-proves the tables: a hand-baked derivation snapshot, not a projection",
    "reference/mcp-catalog.mdx": "frontmatter description hand-types '105 MCP server entries … snapshot 2026-04-17' — outside count-drift-gate's checked classes (providers · builtins · extract modes), so it can rot silently",
}


_VIDEO_STEMS = None


def video_stems() -> set:
    global _VIDEO_STEMS
    if _VIDEO_STEMS is None:
        _VIDEO_STEMS = {pathlib.Path(f).stem for f in tracked_files()
                        if f.startswith("videos/") and f.endswith((".mp4", ".webm"))}
    return _VIDEO_STEMS


def classify(rel: str, body: bytes) -> dict:
    text = None
    try:
        text = body.decode()
    except UnicodeDecodeError:
        pass

    # Generated snippets — ONLY when the in-file marker is present.
    if (rel in GENERATED_SNIPPETS and text is not None
            and "AUTO-GENERATED by" in "\n".join(text.splitlines()[:4])):
        spec = GENERATED_SNIPPETS[rel]
        out = {"class": "generated", "evidence": spec["evidence"],
               "derivation": spec["derivation"]}
        if "note" in spec:
            out["note"] = spec["note"]
        return out

    if rel in AUTHORED_EVIDENCE:
        out = {"class": "authored", "evidence": AUTHORED_EVIDENCE[rel]}
        if rel in AUTHORED_NOTES:
            out["note"] = AUTHORED_NOTES[rel]
        return out

    # Docs pages: authored by construction (AGENTS.md rule 1 — pages import
    # the generated snippets; volatile counts never live in page bodies).
    if rel.endswith(".mdx") and text is not None:
        out = {"class": "authored",
               "evidence": "hand-written MDX page (frontmatter + prose · no generation marker · volatile counts import the generated snippets per AGENTS.md rule 1)"}
        if rel in MDX_NOTES:
            out["note"] = MDX_NOTES[rel]
        return out

    # Media — no in-repo derivation evidence exists for any of it; tailored
    # evidence per family, honest unverified-default on all of it.
    if rel.startswith("videos/") and rel.endswith((".mp4", ".webm")):
        return {"class": "authored",
                "evidence": "screen-capture demo video (poster twin under images/) · recording pipeline is not in this repo",
                "note": "unverified-default"}
    if rel.startswith("images/") and rel.endswith(".png"):
        stem = pathlib.Path(rel).stem
        if stem in video_stems():
            return {"class": "authored",
                    "evidence": f"poster frame paired with videos/{stem}.mp4/.webm (wired as the <video poster=…>) · extraction pipeline is not in this repo",
                    "note": "unverified-default"}
        if stem.startswith("og-"):
            return {"class": "authored",
                    "evidence": "Open Graph card bitmap wired in docs.json metadata · production pipeline is not in this repo",
                    "note": "unverified-default"}
        return {"class": "authored",
                "evidence": "bitmap asset · no in-repo derivation evidence",
                "note": "unverified-default"}
    if rel.startswith("images/") and rel.endswith(".svg"):
        return {"class": "authored",
                "evidence": "brand vector asset (logo/favicon family) · the brand pipeline lives outside this repo",
                "note": "unverified-default"}

    # No evidence → honesty over completeness.
    return {"class": "authored", "evidence": "no generation marker or known role found",
            "note": "unverified-default"}


def q(s) -> str:
    """A JSON string is a valid YAML scalar — deterministic quoting for free."""
    return json.dumps(s, ensure_ascii=False)


def render() -> str:
    rows = []
    counts = {c: 0 for c in CLASSES}
    unverified = 0
    for rel in tracked_files():
        body = (ROOT / rel).read_bytes()
        row = classify(rel, body)
        row["path"] = rel
        row["sha256"] = hashlib.sha256(body).hexdigest()
        counts[row["class"]] += 1
        if row.get("note") == "unverified-default":
            unverified += 1
        rows.append(row)

    lines = [
        "# GENERATED by scripts/estate.py — do not hand-edit.",
        "# The estate manifest: every tracked file declares its provenance.",
        "# OBSERVATION MODE (E0): this declares what IS — it enforces nothing.",
        "# Re-generate: python3 scripts/estate.py --write",
        "# Check:       python3 scripts/estate.py --check   (re-emits · byte-compares · exit 5 on divergence)",
        f"estate_schema: {ESTATE_SCHEMA}",
        "mode: observation",
        "repo: supernovae-st/nika-docs",
        "classes:",
    ]
    for c in CLASSES:
        lines.append(f"  {c}: {q(CLASSES[c])}")
    lines.append("summary:")
    for c in CLASSES:
        lines.append(f"  {c}: {counts[c]}")
    lines.append(f"  unverified-default: {unverified}")
    lines.append("files:")
    for row in rows:
        lines.append(f"- path: {q(row['path'])}")
        lines.append(f"  class: {row['class']}")
        lines.append(f"  sha256: {row['sha256']}")
        lines.append(f"  evidence: {q(row['evidence'])}")
        if "derivation" in row:
            d = row["derivation"]
            lines.append("  derivation:")
            lines.append(f"    tool: {q(d['tool'])}")
            lines.append(f"    gate: {q(d['gate'])}")
            lines.append("    inputs:")
            for i in d["inputs"]:
                lines.append(f"    - {q(i)}")
        if "note" in row:
            lines.append(f"  note: {q(row['note'])}")
    return "\n".join(lines) + "\n"


def main() -> int:
    mode = sys.argv[1] if len(sys.argv) > 1 else "--check"
    if mode not in ("--write", "--check"):
        print(f"estate.py: unknown mode {mode!r} (--write | --check)", file=sys.stderr)
        return 2
    rendered = render()
    if mode == "--write":
        ESTATE.write_text(rendered)
        n = rendered.count("\n- path: ")
        print(f"✓ estate.yaml · {n} files classified")
        return 0
    if not ESTATE.is_file() or ESTATE.read_text() != rendered:
        print("✗ estate drift · estate.yaml diverges from the tracked tree — run scripts/estate.py --write", file=sys.stderr)
        return 5
    print("✓ estate.yaml in sync with the tracked tree")
    return 0


if __name__ == "__main__":
    sys.exit(main())
