#!/usr/bin/env python3
"""Deterministic MDX mirror; prose enrichment stays in authored guide pages."""
import argparse
import hashlib
import html
import json
from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT/'snippets/data/language-reference.json'
TAXONOMY=ROOT/'snippets/data/knowledge-taxonomy.json'
MARKER='{/* GENERATED by scripts/knowledge-mirror.py; edit the spec source or the generator. */}'
def prose(s):return html.escape(str(s),quote=False).replace('{','&#123;').replace('}','&#125;').replace('|','&#124;')
def front(title,desc):return f'---\ntitle: {json.dumps(title)}\ndescription: {json.dumps(desc)}\n---\n\n{MARKER}\n\n'
def sections(snapshot):
    groups=json.loads(TAXONOMY.read_text())['languageSections']
    result={group['title']:[] for group in groups}
    for word in snapshot['words']:
        contexts=[c['context'] for c in word['contracts']]
        group=next((g for g in groups if any(c in g['exactContexts'] or any(c.startswith(p) for p in g['prefixes']) for c in contexts)),None)
        if group is None:raise ValueError('Unclassified schema context: '+word['name'])
        result[group['title']].append(word)
    return result

def render(snapshot):
    words=snapshot['words'];known={w['name'] for w in words};outputs={};rev=snapshot['revision']
    if snapshot['kind']!='spec-language-knowledge' or not re.fullmatch('[a-f0-9]{40}',rev):raise ValueError('Invalid pinned spec knowledge input')
    ids=[w['id'] for w in words]
    if len(ids)!=len(set(ids)):raise ValueError('Duplicate canonical identity')
    for w in words:
        name=w['name'];path=w['docsPath']
        if path!='reference/language/words/'+name or not re.fullmatch('[a-z][a-z0-9_]*',name):raise ValueError('Invalid generated destination')
        lines=[front(name,'Contract, placement, related fields and source examples for this Nika YAML field.'),f'[Language reference](/reference/language/overview) / `{name}`\n',f'## Meaning and placement\n']
        for c in w['contracts']:
            d=c['declaration'];scope=c['context'];label='document' if scope == '/' else scope.removeprefix('/$defs/').replace('/properties/',' → ').replace('/',' · ')
            lines += [f'### {prose(label)}\n',prose(d.get('description','The schema declares this field at the location below.'))+'\n', '| Property | Declaration |','| --- | --- |',f'| Requirement | {"Required in this object" if c["required"] else "Optional in this object"} |',f'| Schema location | `{c["pointer"]}` |']
            for key in ['type','$ref','default','const','enum','minimum','maximum','minLength','maxLength','pattern','additionalProperties']:
                if key in d:lines.append(f'| {prose(key)} | {prose(json.dumps(d[key],ensure_ascii=False))} |')
            siblings=[s for s in c['siblings'] if s in known]
            if siblings:lines+=['\n**In the same object:** '+ ' · '.join(f'[{s}](/reference/language/words/{s})' for s in siblings)+'\n']
            lines+=[f'\n[Schema source (use the pointer above)](https://github.com/supernovae-st/nika-spec/blob/{rev}/schemas/workflow.schema.json)\n']
        if w['examples']:
            ex=w['examples'][0];lines+=['## In a source template\n',f'Excerpt from `{ex["path"]}`, source lines {ex["startLine"]}–{ex["endLine"]}. This is a fragment, not a runnable workflow.\n','```yaml illustration',ex['excerpt'],'```','\n### Templates containing this field\n','| Template | Source |','| --- | --- |']
            for e in w['examples']:lines.append(f'| `{e["path"]}` | [Line {e["line"]}](https://github.com/supernovae-st/nika-spec/blob/{rev}/{e["path"]}#L{e["line"]}) |')
            lines+=['\nThese are literal key occurrences in the source files, not an execution or conformance claim. [How to instantiate a template](/guides/templates).\n']
        else:lines+=['## Examples\n','No matching source-template occurrence is recorded in this projection. [Write a workflow](/guides/templates) or consult the schema declaration above.\n']
        lines+=['## Contract and implementation\n','This page projects the named specification revision. Check [released engine status](/reference/status) and [the validation workflow](/guides/agent-authoring) before running a file. An optional field is not evidence that every engine supports every value.\n',f'Canonical identity: `{w["id"]}`. Spec revision: [`{rev[:12]}`](https://github.com/supernovae-st/nika-spec/tree/{rev}).\n','[How documentation stays connected](/reference/knowledge-system).\n']
        outputs[path+'.mdx']='\n'.join(lines)
    overview=front('Language field reference','Find a YAML field by name, understand its scope, and follow its contract and examples.')
    overview+='This reference is generated from the specification schema. Fields with the same spelling share one page with their separate placement contracts. The schema defines the language; [engine status](/reference/status) identifies the released implementation.\n\n'
    overview+='## Start with the shape\n\n[Workflow syntax](/reference/yaml-syntax) · [Bindings and dependencies](/concepts/bindings) · [Verbs](/concepts/verbs) · [Security](/concepts/security)\n'
    for title,group in sections(snapshot).items():
        if not group:continue
        overview+=f'\n## {title}\n\n| Field | Declared in |\n| --- | --- |\n'
        for w in group:overview+=f'| [{w["name"]}](/{w["docsPath"]}) | '+prose(' · '.join(sorted({c['context'] or '/' for c in w['contracts']})))+' |\n'
    outputs['reference/language/overview.mdx']=overview
    manifest={'schemaVersion':1,'kind':'public-documentation-mirror','specRevision':rev,'sourceSha256':hashlib.sha256((json.dumps(snapshot,ensure_ascii=False,indent=2)+'\n').encode()).hexdigest(),'entries':[{'id':w['id'],'path':w['docsPath'],'url':'https://docs.nika.sh/'+w['docsPath'],'relation':'exact','publication':'not-verified','sourcePointers':[c['pointer'] for c in w['contracts']],'sha256':hashlib.sha256(outputs[w['docsPath']+'.mdx'].encode()).hexdigest()} for w in words]}
    outputs['snippets/data/knowledge-mirror.json']=json.dumps(manifest,ensure_ascii=False,indent=2)+'\n'
    return outputs

def main():
    p=argparse.ArgumentParser();p.add_argument('--write',action='store_true');p.add_argument('--source',type=Path);a=p.parse_args()
    if a.source:
        if not a.write:raise SystemExit('--source requires --write')
    source_text=(a.source if a.source else SOURCE).read_text()
    snapshot=json.loads(source_text);outputs=render(snapshot)
    nav=json.loads((ROOT/'docs.json').read_text())
    ref=next(t for t in nav['navigation']['tabs'] if t['tab']=='Reference')
    ref['groups']=[g for g in ref['groups'] if g['group'] not in ['Language fields','Documentation system']]
    ref['groups'].insert(1,{'group':'Language fields','pages':['reference/language/overview',*[{'group':title,'pages':[w['docsPath'] for w in group]} for title,group in sections(snapshot).items() if group]]})
    ref['groups'].append({'group':'Documentation system','pages':['reference/knowledge-system']})
    outputs['docs.json']=json.dumps(nav,ensure_ascii=False,indent=2)+'\n'
    actual=set(p.relative_to(ROOT).as_posix() for p in (ROOT/'reference/language').rglob('*.mdx')) if (ROOT/'reference/language').exists() else set()
    extra=actual-set(outputs)
    if extra:raise SystemExit(f'Unexpected generated pages require explicit removal review: {sorted(extra)}')
    # A rejected candidate must leave the admitted source intact.
    if a.write and a.source:SOURCE.write_text(source_text)
    for name,text in outputs.items():
        file=ROOT/name
        if a.write:file.parent.mkdir(parents=True,exist_ok=True);file.write_text(text)
        elif not file.exists() or file.read_text()!=text:raise SystemExit('Documentation drift: '+name)
    print(f'{"Wrote" if a.write else "Verified"} {len(snapshot["words"])} word pages, index, navigation and identity manifest')
if __name__=='__main__':main()
