#!/usr/bin/env python3
"""Project public tool contracts from pinned spec Git objects, never marketing pages."""
import argparse, hashlib, html, json, posixpath, re, subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT/'snippets/data/tool-reference.json'
MARKER='{/* GENERATED by scripts/tool-reference.py; edit the spec or generator. */}'
def digest(text):return hashlib.sha256(text.encode()).hexdigest()
def acquire(root):
    import yaml
    revision=subprocess.check_output(['git','rev-parse','HEAD'],cwd=root,text=True).strip()
    paths=['canon/builtins.yaml','stdlib/builtins-v0.1.md']
    raw={p:subprocess.check_output(['git','show',f'{revision}:{p}'],cwd=root,text=True) for p in paths}
    for path,text in raw.items():
        if (root/path).read_text()!=text:raise ValueError('Uncommitted contract: '+path)
    return dict(revision=revision,inputs={p:digest(t) for p,t in raw.items()},registry=yaml.safe_load(raw[paths[0]])['builtins'],contract=raw[paths[1]])
def mdx(text,revision):
    # Keep code literal. Escape MDX outside code; resolve source-relative links
    # against the pinned spec, never against a same-named documentation page.
    pieces=re.split(r'(```[^\n]*\n[\s\S]*?```|`[^`\n]+`)',text)
    def convert(part):
        if part.startswith('```'):return re.sub(r'^```ya?ml[^\n]*', '```yaml illustration',part)
        if part.startswith('`'):return part
        part=re.sub(r'\]\(([^)\s]+)\)',lambda m:']('+('https://github.com/supernovae-st/nika-spec/blob/'+revision+'/'+posixpath.normpath(posixpath.join('stdlib',m[1])) if not re.match(r'https?://',m[1]) else m[1])+')',part)
        return html.escape(part,quote=False).replace('{','&#123;').replace('}','&#125;')
    return ''.join(map(convert,pieces))
def render(source):
    rev=source['revision']
    if not re.fullmatch('[a-f0-9]{40}',rev):raise ValueError('Invalid revision')
    lines=source['contract'].splitlines();sections={};active=None;fence=False
    for index,line in enumerate(lines):
        if line.startswith('```'):fence=not fence
        if not fence and re.match(r'^#{1,3} ',line):
            if active:sections[active]['end']=index;active=None
            match=re.match(r'^### `nika:([a-z_]+)`',line)
            if match:
                active=match[1]
                if active in sections:raise ValueError('Duplicate tool section: '+active)
                sections[active]={'start':index,'end':len(lines)}
    rows=sorted(source['registry'],key=lambda r:r['id']);names=[r['id'].removeprefix('nika:') for r in rows]
    if len(set(names))!=len(names) or set(names)!=set(sections):raise ValueError('Registry and prose membership differ')
    outputs={};entries=[]
    for row in rows:
        name=row['id'].removeprefix('nika:');section=sections[name];path='reference/tools/'+name
        if not re.fullmatch('[a-z_]+',name):raise ValueError('Invalid tool identity')
        contract='\n'.join(lines[section['start']+1:section['end']]).strip()
        url=f'https://github.com/supernovae-st/nika-spec/blob/{rev}/stdlib/builtins-v0.1.md#L{section["start"]+1}'
        text=f'''---
title: "nika:{name}"
description: "Usage, declared contract and source links for this Nika builtin."
icon: "toolbox"
---

{MARKER}

import {{ Ecosystem }} from "/snippets/_ecosystem.mdx";

[Builtins catalog](/reference/builtins) / `nika:{name}`

<CardGroup cols={{2}}>
  <Card title="{row['category'].capitalize()}" icon="layer-group">Tool family from the canonical registry.</Card>
  <Card title="invoke" icon="code" href="/reference/language/words/invoke">Call this builtin through the invoke verb.</Card>
</CardGroup>

## Read this contract

This reference preserves the specification at the revision linked below. Source examples are **fragments**: their surrounding tasks, inputs and permissions are not supplied here. Consult [engine status](/reference/status) and `nika catalog --tools --json` for the installed implementation; a registry declaration is not a runtime qualification.

## Usage and behavior

{mdx(contract,rev)}

## Related concepts

<CardGroup cols={{2}}>
  <Card title="Arguments" icon="sliders" href="/reference/language/words/args">Pass the values required by the tool contract.</Card>
  <Card title="Permissions" icon="shield" href="/concepts/security">Understand authority before granting effects.</Card>
  <Card title="Errors and recovery" icon="rotate" href="/reference/error-codes">Read diagnostics and choose a recovery policy.</Card>
  <Card title="Workflow templates" icon="file-code" href="/guides/templates">Put the fragment inside a complete workflow.</Card>
</CardGroup>

## Contract provenance

[Read the pinned specification]({url}) · [Canonical registry](https://github.com/supernovae-st/nika-spec/blob/{rev}/canon/builtins.yaml).

Tool identity: `nika:{name}`. Specification revision: `{rev[:12]}`.

<Ecosystem />
'''
        outputs[path+'.mdx']=text
        entries.append(dict(path=path,ids=['nika:'+name],legacyPaths=['/language/stdlib/'+name],sha256=digest(text),source=url,revision=rev))
    outputs['snippets/data/tool-mirror.json']=json.dumps(dict(schemaVersion=1,revision=rev,inputs=source['inputs'],entries=entries),indent=2)+'\n'
    return outputs

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--spec-root',type=Path);parser.add_argument('--write',action='store_true');parser.add_argument('--verify-spec-root',type=Path);args=parser.parse_args()
    if args.spec_root and not args.write:raise ValueError('--spec-root requires --write')
    source=acquire(args.spec_root) if args.spec_root else json.loads(SOURCE.read_text())
    if args.verify_spec_root:
        import yaml
        raw={p:subprocess.check_output(['git','show',f'{source["revision"]}:{p}'],cwd=args.verify_spec_root,text=True) for p in source['inputs']}
        if {p:digest(t) for p,t in raw.items()}!=source['inputs']:raise ValueError('Source fingerprints differ')
        if raw['stdlib/builtins-v0.1.md']!=source['contract'] or yaml.safe_load(raw['canon/builtins.yaml'])['builtins']!=source['registry']:raise ValueError('Snapshot differs from pinned spec')
    outputs=render(source)
    nav=json.loads((ROOT/'docs.json').read_text());ref=next(t for t in nav['navigation']['tabs'] if t['tab']=='Reference')
    ref['groups']=[g for g in ref['groups'] if g['group']!='Tool contracts']
    categories=sorted({r['category'] for r in source['registry']})
    ref['groups'].append({'group':'Tool contracts','pages':[{'group':c.capitalize(),'pages':['reference/tools/'+r['id'].removeprefix('nika:') for r in sorted(source['registry'],key=lambda r:r['id']) if r['category']==c]} for c in categories]})
    outputs['docs.json']=json.dumps(nav,ensure_ascii=False,indent=2)+'\n'
    if args.write and args.spec_root:SOURCE.write_text(json.dumps(source,ensure_ascii=False,indent=2)+'\n')
    for path,text in outputs.items():
        dest=ROOT/path
        if args.write:dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(text)
        elif not dest.exists() or dest.read_text()!=text:raise ValueError('Tool reference drift: '+path)
    print(f'{"Wrote" if args.write else "Verified"} {len(source["registry"])} tool pages and navigation')
if __name__=='__main__':main()
